In [1]:
import numpy as np

In [2]:
vector_row = np.array([[1,2,3,4,5,6]])
vector_col = np.array([[1],[2],[3],[4],[5]])

print(vector_row.shape)
print(vector_col.shape)

(1, 6)
(5, 1)


In [3]:
# Transpose the vector

from numpy.linalg import norm

new_vector = vector_row.T
print(new_vector)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [4]:
norm_1 = norm(new_vector,1)

In [5]:
#The norm of a vector is a measure of its length
norm_2 = norm(new_vector,2)
norm_inf = norm(new_vector,np.inf)

print("L_1 is: %0.1f"%norm_1)
print("L_2 is: %0.1f"%norm_2)
print("L_3 is:%0.1f"%norm_inf)

L_1 is: 21.0
L_2 is: 9.5
L_3 is:6.0


In [9]:
# Dot Product of Vectors  (v.w)

from numpy import arccos, dot

v = np.array([[10,9,3]])
w = np.array([[2,5,12]])
theta = arccos(dot(v,w.T)/(norm(v)*norm(w)))
print(theta)

[[0.97992471]]


In [10]:
# Cross Product of vectors (v X w)
# The geometric interpretation of the cross product is a vector perpendicular to both v and w with length equal to the area enclosed by the parallelogram created by the two vectors.

v = np.array([[0,2,0]])
w = np.array([[3,0,0]])
print(np.cross(v,w))



[[ 0  0 -6]]


In [11]:
# Linear Combinations of Vector

v = np.array([[0,3,2]])
w = np.array([[4,1,1]])
u = np.array([[0,-2,0]])
X = 3*v-2*w+4*u
print(X)

[[-8 -1  4]]


In [13]:
# Matrix - Dot Product

P = np.array([[1,7],[2,3],[5,0]])
Q = np.array([[2,6,3,1],[1,2,3,4]])
print(P)
print(Q)
print(np.dot(P,Q))
#np.dot(Q,P)

[[1 7]
 [2 3]
 [5 0]]
[[2 6 3 1]
 [1 2 3 4]]
[[ 9 20 24 29]
 [ 7 18 15 14]
 [10 30 15  5]]


In [14]:
# Square matrix - determinant = |M|= ad-bc

from numpy.linalg import det

M = np.array([[0,2,1,3],[3,2,8,1],[1,0,0,3],[0,3,2,1]])

print(M)

print("Determinant: %0.1f"%det(M))
I = np.eye(4)

print("I:",I)
print("M*I:\n",np.dot(M,I))


[[0 2 1 3]
 [3 2 8 1]
 [1 0 0 3]
 [0 3 2 1]]
Determinant: -38.0
I: [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
M*I:
 [[0. 2. 1. 3.]
 [3. 2. 8. 1.]
 [1. 0. 0. 3.]
 [0. 3. 2. 1.]]


In [15]:
# inverse of Matrix ==> M.N = I
# there are matrices that do not have inverses. These matrices are called singular. Matrices that do have an inverse are called nonsingular.
# If the determinant is 0, then the matrix is singular; if not, the matrix is nonsingular.

from numpy.linalg import inv

print("Inverse of M:\n",inv(M))

P = np.array([[0,1,0],[0,0,0],[1,0,1]])

print("determinant of P:",det(P))



Inverse of M:
 [[-1.57894737 -0.07894737  1.23684211  1.10526316]
 [-0.63157895 -0.13157895  0.39473684  0.84210526]
 [ 0.68421053  0.18421053 -0.55263158 -0.57894737]
 [ 0.52631579  0.02631579 -0.07894737 -0.36842105]]
determinant of P: 0.0


In [16]:
# Rank Of Matrix: The rank. of an m×n matrix A is the number of linearly independent columns or rows of A, and is denoted by rank(A).
# A matrix is called full rank. if rank (A)=min(m,n).
# Augmented Matrix ==> [A,y]
# rank([A,y]) = rank(A) + 1

from numpy.linalg import cond, matrix_rank

A = np.array([[1,1,0],[0,1,0],[1,0,1]])

print("Condition number : \n", cond(A))

print("Rank:\n",matrix_rank(A))
y = np.array([[1],[2],[1]])
A_y = np.concatenate((A,y),axis=1)
print("Augmented matrix:\n",A_y)


Condition number : 
 4.048917339522305
Rank:
 3
Augmented matrix:
 [[1 1 0 1]
 [0 1 0 2]
 [1 0 1 1]]


In [17]:

u = np.array([[4,3,-5],
             [0,-2.5,2.5],
              [0,0,12]])
l = np.array([[1,0,0],[-0.5,1,0],[2,-0.8,1]])

print("LU=",np.dot(l,u))


LU= [[ 4.  3. -5.]
 [-2. -4.  5.]
 [ 8.  8.  0.]]


In [18]:
# Gauss - Seidel Method

a = [[8,3,-3],[-2,-8,5],[3,5,10]]

# find diagonal coefficients
diag = np.diag(np.abs(a))

# find row sum without diagonal
off_diag = np.sum(np.abs(a),axis = 1) - diag

if np.all(diag > off_diag):
    print("matrix is diagonally dominant")
else:
    print("Not Diagonally dominant")

matrix is diagonally dominant


In [19]:
x1 = 0
x2 = 0
x3 = 0
epsilon = 0.01
converged = False

x_old = np.array([x1,x2,x3])
print("X_old:",x_old)

print("Iteration results:")
print(' k,    x1,    x2,    x3 ')
for k in range(1, 50):
    x1 = (14-3*x2+3*x3)/8
    x2 = (5+2*x1-5*x3)/(-8)
    x3 = (-8-3*x1-5*x2)/(-5)
    x = np.array([x1, x2, x3])
    # check if it is smaller than threshold
    dx = np.sqrt(np.dot(x-x_old, x-x_old))
    
    print("%d, %.4f, %.4f, %.4f"%(k, x1, x2, x3))
    if dx < epsilon:
        converged = True
        print('Converged!')
        break
        
    # assign the latest x value to the old value
    x_old = x

if not converged:
    print('Not converge, increase the # of iterations')

X_old: [0 0 0]
Iteration results:
 k,    x1,    x2,    x3 
1, 1.7500, -1.0625, 1.5875
2, 2.7437, -0.3188, 2.9275
3, 2.9673, 0.4629, 3.8433
4, 3.0177, 1.0226, 4.4332
5, 3.0290, 1.3885, 4.8059
6, 3.0315, 1.6208, 5.0397
7, 3.0321, 1.7668, 5.1861
8, 3.0322, 1.8582, 5.2776
9, 3.0322, 1.9154, 5.3348
10, 3.0323, 1.9512, 5.3705
11, 3.0323, 1.9735, 5.3929
12, 3.0323, 1.9875, 5.4068
13, 3.0323, 1.9962, 5.4156
14, 3.0323, 2.0017, 5.4210
Converged!


In [20]:
#Use numpy.linalg.solve to solve the following equations.

# 4x1+3x2−5x3 = 2
# −2x1−4x2+5x3 = 5
#  8x1+8x2 = −3

A = np.array([[4,3,-5],
            [-2,-4,5],
            [8,8,0]])
y = np.array([2,5,-3])

x = np.linalg.solve(A,y)

print(x)

[ 2.20833333 -2.58333333 -0.18333333]


In [21]:
A_inv = np.linalg.inv(A)

print("A:\n",A)

print("inverse of A:\n",A_inv)

x = np.dot(A_inv,y)

print(x)

A:
 [[ 4  3 -5]
 [-2 -4  5]
 [ 8  8  0]]
inverse of A:
 [[ 0.33333333  0.33333333  0.04166667]
 [-0.33333333 -0.33333333  0.08333333]
 [-0.13333333  0.06666667  0.08333333]]
[ 2.20833333 -2.58333333 -0.18333333]


In [22]:
from scipy.linalg import lu
print("A:\n",A)

P,L,U = lu(A)

print("P:\n",P)
print("L:\n",L)
print("U:\n",U)
print("LU:\n",np.dot(L,U))



A:
 [[ 4  3 -5]
 [-2 -4  5]
 [ 8  8  0]]
P:
 [[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
L:
 [[ 1.    0.    0.  ]
 [-0.25  1.    0.  ]
 [ 0.5   0.5   1.  ]]
U:
 [[ 8.   8.   0. ]
 [ 0.  -2.   5. ]
 [ 0.   0.  -7.5]]
LU:
 [[ 8.  8.  0.]
 [-2. -4.  5.]
 [ 4.  3. -5.]]


In [23]:
print("P.A:\n",np.dot(P,A))

P.A:
 [[ 8.  8.  0.]
 [-2. -4.  5.]
 [ 4.  3. -5.]]


In [ ]:
########################### Thanks ###########################