In [1]:
import numpy as np

In [2]:
print("Hello")

Hello


In [3]:
a = np.diag([1,2,3,4,5])
a

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [4]:
np.diag(a)

array([1, 2, 3, 4, 5])

In [5]:
a = np.random.rand(5)
a

array([0.42170277, 0.63298336, 0.61082744, 0.83532549, 0.87040838])

In [6]:
a = np.random.randn(5)
a

array([ 0.78855027,  0.08388371, -0.07318452, -0.97266004, -0.03870472])

In [9]:
a = np.arange(10)
a.dtype
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
a = np.arange(10,dtype="float64")
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [13]:
a = np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [14]:
d = np.array([1+2j,2+4j])
d

array([1.+2.j, 2.+4.j])

In [15]:
print(d.dtype)

complex128


In [16]:
b = np.array([True,False,True,False])
b

array([ True, False,  True, False])

In [18]:
# indexing slicing

a = np.arange(10)
print(a[5])

5


In [19]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
a = np.diag([1,2,3,4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [21]:
a[2,3]

0

In [22]:
a[3,3]

4

In [23]:
a[2,3]=5
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 5],
       [0, 0, 0, 4]])

In [24]:
a = np.arange(10)

In [25]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
a[1:8:2]

array([1, 3, 5, 7])

In [29]:
a[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
a[5:]

array([5, 6, 7, 8, 9])

In [31]:
a[4::3]

array([4, 7])

In [32]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [33]:
a[2::-1]

array([2, 1, 0])

In [34]:
a[:2:-1]

array([9, 8, 7, 6, 5, 4, 3])

In [36]:
a[:5:1]

array([0, 1, 2, 3, 4])

In [37]:
# Copy & Views
a = np.arange(10)

a


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
b = a[:4]
b

array([0, 1, 2, 3])

In [39]:
np.shares_memory(a,b)

True

In [40]:
b[0]=10
b

array([10,  1,  2,  3])

In [41]:
a

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [42]:
c = np.copy(a)

In [43]:
c

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [44]:
np.shares_memory(a,c)

False

In [45]:
c[0]=11
c


array([11,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [46]:
a

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [47]:
d = a.copy()

In [48]:
d

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [49]:
np.shares_memory(a,d)

False

In [50]:
# Fancy Indexing

a = np.random.randint(0,20,15)
a

array([10,  9,  6,  8,  6, 13,  1,  0, 11,  7, 13,  9,  7,  0, 15])

In [51]:
mask = (a % 2 == 0)


In [52]:
extract_from_a = a[mask]
extract_from_a

array([10,  6,  8,  6,  0,  0])

In [53]:
a[mask]=-1

In [54]:
a

array([-1,  9, -1, -1, -1, 13,  1, -1, 11,  7, 13,  9,  7, -1, 15])

In [55]:
a = np.arange(0,100,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [56]:
a[[2,3,4,2,6,4]]

array([20, 30, 40, 20, 60, 40])

In [57]:
a[[2,6,7]]=-100

In [58]:
a

array([   0,   10, -100,   30,   40,   50, -100, -100,   80,   90])

In [59]:
# Elementwise Operations

a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [60]:
a+1

array([2, 3, 4, 5, 6])

In [61]:
a+5

array([ 6,  7,  8,  9, 10])

In [62]:
c = a+10

In [63]:
c

array([11, 12, 13, 14, 15])

In [64]:
np.shares_memory(a,c)

False

In [65]:
d = a **2

In [66]:
d

array([ 1,  4,  9, 16, 25], dtype=int32)

In [67]:
b = np.ones(4)+1
b

array([2., 2., 2., 2.])

In [68]:
b-2

array([0., 0., 0., 0.])

In [69]:
a = [1,2,3,4]
b = [1,2,3]
a+b

[1, 2, 3, 4, 1, 2, 3]

In [70]:
a

[1, 2, 3, 4]

In [73]:
c = np.diag([3,4,5,6])

In [74]:
c

array([[3, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 6]])

In [75]:
c*c

array([[ 9,  0,  0,  0],
       [ 0, 16,  0,  0],
       [ 0,  0, 25,  0],
       [ 0,  0,  0, 36]])

In [76]:
c.dot(c)

array([[ 9,  0,  0,  0],
       [ 0, 16,  0,  0],
       [ 0,  0, 25,  0],
       [ 0,  0,  0, 36]])

In [77]:
c == c


array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [78]:
a == c

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [80]:
a = [1,2,3,4]
b=[3,1,4,1]
a == b

False

In [81]:
a = np.array([1,2,3,4])
b = np.array([1,1,3,5])
a ==b

array([ True, False,  True, False])

In [82]:
a > b

array([False,  True, False, False])

In [83]:
np.array_equal(a,b)

False

In [84]:
np.logical_and(a,b)

array([ True,  True,  True,  True])

In [85]:
np.logical_or(a,b)

array([ True,  True,  True,  True])

In [86]:
c = np.array([1,0,0,1])
c

array([1, 0, 0, 1])

In [87]:
np.logical_and(a,c)

array([ True, False, False,  True])

In [88]:
np.logical_or(a,c)

array([ True,  True,  True,  True])

In [89]:
# Transcendental function

a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [90]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [91]:
np.log(a)

<ipython-input-91-89b6b8e53c58>:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [92]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [93]:
# shape Mismatch

a = np.arange(4)
a

array([0, 1, 2, 3])

In [95]:
a + np.array([1,2,3,4])

array([1, 3, 5, 7])

In [96]:
# Basic Reductions

x = np.array([1,2,3,4])
np.sum(x)

10

In [97]:
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [98]:
x.sum(axis = 0)

array([4, 6])

In [99]:
x.sum(axis=1)

array([3, 7])

In [100]:
x.min()

1

In [101]:
x.max()

4

In [102]:
x.argmin()

0

In [103]:
x.argmax()

3

In [104]:
# logical Operation
np.all([True,True,False])

False

In [105]:
np.any([True,False])

True

In [106]:
np.any([False,False])

False

In [108]:
a = np.array([1,2,3,2])
b= np.array([2,2,3,2])
c = np.array([6,4,4,5])
((a <= b) & ( b <=c)).all()

True

In [109]:
x = np.array([1,2,3,1])
y = np.array([[1,2,3],[5,6,1]])
x.mean()

1.75

In [110]:
np.median(x)

1.5

In [111]:
np.median(y,axis=-1)

array([2., 5.])

In [112]:
x.std()

0.82915619758885

In [117]:
# load data into numpy array object

data = np.loadtxt("demo.txt")

In [118]:
data

array([  1.23  ,   2.334 ,   0.2321, 123.    ])

In [119]:
first,second,third,forth = data.T
print(first)
print(second)
print(third)
print(forth)

1.23
2.334
0.2321
123.0


In [124]:
data1 = data[:]

In [122]:
data1

array([  1.23  ,   2.334 ,   0.2321, 123.    ])

In [125]:
data1.std(axis=0) # column wise std

52.71788496944727

In [128]:
data1.argmax() 

3

In [132]:
# Broadcasting

a = np.tile(np.arange(0,40,10),(4,1))
a


array([[ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30]])

In [136]:
a = a.T

In [134]:
b = np.array([10,1,2])
b

array([10,  1,  2])

In [138]:
a.shape


(4, 4)

In [143]:
b = np.arange(0,20,10)
b.shape
b = b[:,np.newaxis]
b.shape

(2, 1)

In [144]:
# Array Shape Manipulation

# Flattering

a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [145]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [146]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [148]:
b = a.ravel()

In [149]:
b

array([1, 2, 3, 4, 5, 6])

In [150]:
b = b.reshape((2,3))

In [151]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [152]:
b[0,0]=100
b

array([[100,   2,   3],
       [  4,   5,   6]])

In [153]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [155]:
a[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [156]:
a.shape

(3,)

In [165]:
a = np.array([[1,4,2],[3,2,5]])
b = np.argsort(a)
a = np.sort(a,axis=1)
a
b

array([[0, 2, 1],
       [1, 0, 2]], dtype=int64)

a[b]

In [167]:
########################################