In [1]:
print("A")

A


In [25]:
import tensorflow as tf
import pandas as pd

In [3]:
print(("Your Tensor flow version: {0}").format(tf.__version__))

Your Tensor flow version: 2.6.0


In [4]:
A = tf.constant([[1,2],[3,4]])
A

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [5]:
B = tf.Variable([[1,2],[3,4]])
B

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [6]:
AB_Concatenated = tf.concat(values = [A,B],axis = 1)
AB_Concatenated

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 1, 2],
       [3, 4, 3, 4]])>

In [7]:
AB_Concatenated_1 = tf.concat(values = [A,B],axis = 0)
AB_Concatenated_1

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])>

In [8]:
tensor = tf.zeros(shape=[3,4],dtype = tf.int32)
tensor

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])>

In [9]:
tensor_1 = tf.ones(shape=[3,4],dtype = tf.int32)
tensor_1

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])>

In [10]:
tensor_1 = tf.ones(shape=[3,4],dtype = tf.float32)
tensor_1

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [11]:
reshaped_tensor = tf.reshape(tensor = tensor_1, shape = [4,3])
reshaped_tensor

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [12]:
D = tf.random.uniform(shape=[3,4])
D

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.6301898 , 0.49578655, 0.61417174, 0.38227022],
       [0.81323564, 0.66888857, 0.98950124, 0.46218598],
       [0.13209093, 0.09898376, 0.78129244, 0.20528436]], dtype=float32)>

In [13]:
reshaped_D = tf.reshape(tensor = D, shape = [4,3])
reshaped_D

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[0.6301898 , 0.49578655, 0.61417174],
       [0.38227022, 0.81323564, 0.66888857],
       [0.98950124, 0.46218598, 0.13209093],
       [0.09898376, 0.78129244, 0.20528436]], dtype=float32)>

In [14]:
# type-cast 
D_int = tf.cast(D,tf.int32)
print(D)
print(D_int)

tf.Tensor(
[[0.6301898  0.49578655 0.61417174 0.38227022]
 [0.81323564 0.66888857 0.98950124 0.46218598]
 [0.13209093 0.09898376 0.78129244 0.20528436]], shape=(3, 4), dtype=float32)
tf.Tensor(
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)


In [15]:
a = tf.transpose(D)
a

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[0.6301898 , 0.81323564, 0.13209093],
       [0.49578655, 0.66888857, 0.09898376],
       [0.61417174, 0.98950124, 0.78129244],
       [0.38227022, 0.46218598, 0.20528436]], dtype=float32)>

In [19]:
# matrix multiplication
R = tf.constant([[5,8],[3,9]])
S = tf.constant([[4],[2]])
R_X_S = tf.matmul(R,S)
R_X_S

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[36],
       [30]])>

In [21]:
# Element-wise multiply
R_S = tf.multiply(R,S)
R_S

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 32],
       [ 6, 18]])>

In [32]:
# Identity Matrix
T = tf.constant([[4,9],[5,6],[1,8]])
rows, columns = T.shape
print("row:",rows,"columns:",columns)
Identity_T = tf.eye(num_rows = rows,num_columns = columns, dtype= tf.int32)

Identity_T

row: 3 columns: 2


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 0],
       [0, 1],
       [0, 0]])>

In [35]:
# Import The Important Libraries

import datetime, warnings, scipy
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib as mpl
import matplotlib.pyplot as plt
plt.rcParams["patch.force_edgecolor"]=True
plt.style.use("fivethirtyeight")
mpl.rc("patch",edgecolor = "dimgray", linewidth = 1)
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "last_expr"
pd.options.display.max_columns = 50
%matplotlib inline
warnings.filterwarnings("ignore")


In [37]:
import math
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.metrics import mean_squared_error


In [ ]:
print("Testing")